source 'https://rubygems.org'

gem 'rake'
gem 'dashing'
gem 'json', '~> 1.8.2'
gem 'dotenv'
gem 'octokit'
gem 'i18n'
gem 'faraday', '~> 1.0'
gem 'faraday-http-cache'
gem 'activesupport'
gem 'rspec'
gem 'rspec-mocks'
gem "sentry-raven" 
gem 'typhoeus'
